# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: Swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Unidirectional.xcworkspace -scheme Unidirectional-Example ONLY_ACTIVE_ARCH=NO -allowProvisioningUpdates -allowProvisioningDeviceRegistration -sdk iphonesimulator12.0 | xcpretty
- pod lib lint
